### ISSUE TITLE
Section 53.3.1 Strange output after adding Cheese List Test

### ISSUE THREAD

**Issue by SmartC2016** [roygreenfeld/django-crash-course#116]
## Location within the Book

* Chapter or Appendix: 53
* Section: 3
* Subsection: 1

## Description 
After adding the new test code for the Cheese List view, I receive this output at the very end of testing:

```
Results (1.59s):
      11 passed
Can't add file tracer data for unmeasured file '/Users/yyy/django_crash/everycheese/everycheese/everycheese/templates/cheeses/cheese_list.html'
```

There is a lot of ```everycheese``` in the path, but where does it come from?!

**Comment by omaciel** [comment]
My output shows that I have 11 tests passing and 1 failing with the underlying issue potentially related to [this](https://github.com/django-compressor/django-compressor/pull/206)?

```
―――――――――――――――――――――――――――――――――――――――――――――――――――――――――― test_good_cheese_list_view_expanded ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

rf = <django.test.client.RequestFactory object at 0x106d01a30>

    def test_good_cheese_list_view_expanded(rf):
        # Determine the URL
        url = reverse("cheeses:list")
        # rf is pytest shortcut to django.test.RequestFactory
        # We generate a request as if from a user accessing # the cheese list view
        request = rf.get(url)
        # Call as_view() to make a callable object
        # callable_obj is analogous to a function-based view
        callable_obj = CheeseListView.as_view()
        # Pass in the request into the callable_obj to get an
        # HTTP response served up by Django
        response = callable_obj(request)
        # Test that the HTTP response has 'Cheese List' in the
        # HTML and has a 200 response code
>       assertContains(response, 'Cheese List')

everycheese/cheeses/tests/test_views.py:36: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/pytest_django/asserts.py:18: in assertion_func
    return func(*args, **kwargs)
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/django/test/testcases.py:445: in assertContains
    text_repr, real_count, msg_prefix = self._assert_contains(
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/django/test/testcases.py:410: in _assert_contains
    response.render()
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/django/template/response.py:105: in render
    self.content = self.rendered_content
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/django/template/response.py:83: in rendered_content
    return template.render(context, self._request)
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/django/template/backends/django.py:61: in render
    return self.template.render(context)
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/django/template/base.py:171: in render
    return self._render(context)
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/django/test/utils.py:95: in instrumented_test_render
    return self.nodelist.render(context)
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/django/template/base.py:936: in render
    bit = node.render_annotated(context)
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/django/template/base.py:903: in render_annotated
    return self.render(context)
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/django/template/loader_tags.py:150: in render
    return compiled_parent._render(context)
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/django/test/utils.py:95: in instrumented_test_render
    return self.nodelist.render(context)
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/django/template/base.py:936: in render
    bit = node.render_annotated(context)
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/django/template/base.py:903: in render_annotated
    return self.render(context)
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/django/template/loader_tags.py:62: in render
    result = block.nodelist.render(context)
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/django/template/base.py:936: in render
    bit = node.render_annotated(context)
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/django/template/base.py:903: in render_annotated
    return self.render(context)
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/compressor/templatetags/compress.py:143: in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/compressor/templatetags/compress.py:111: in render_compressed
    cache_key, cache_content = self.render_cached(compressor, kind, mode)
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/compressor/templatetags/compress.py:89: in render_cached
    cache_key = get_templatetag_cachekey(compressor, mode, kind)
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/compressor/cache.py:104: in get_templatetag_cachekey
    "templatetag.%s.%s.%s" % (compressor.cachekey, mode, kind))
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/django/utils/functional.py:48: in __get__
    res = instance.__dict__[self.name] = self.func(instance)
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/compressor/base.py:200: in cachekey
    [self.content] + self.mtimes).encode(self.charset), 12)
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/django/utils/functional.py:48: in __get__
    res = instance.__dict__[self.name] = self.func(instance)
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/compressor/base.py:194: in mtimes
    for kind, value, basename, elem in self.split_contents()
../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/compressor/js.py:17: in split_contents
    filename = self.get_filename(basename)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <compressor.js.JsCompressor object at 0x106ce33d0>, basename = 'js/vendors.js'

    def get_filename(self, basename):
        """
        Returns full path to a file, for example:
    
        get_filename('css/one.css') -> '/full/path/to/static/css/one.css'
        """
        filename = None
        # First try finding the file using the storage class.
        # This is skipped in DEBUG mode as files might be outdated in
        # compressor's final destination (COMPRESS_ROOT) during development
        if not settings.DEBUG:
            try:
                # call path first so remote storages don't make it to exists,
                # which would cause network I/O
                filename = self.storage.path(basename)
                if not self.storage.exists(basename):
                    filename = None
            except NotImplementedError:
                # remote storages don't implement path, access the file locally
                if compressor_file_storage.exists(basename):
                    filename = compressor_file_storage.path(basename)
        # secondly try to find it with staticfiles
        if not filename and self.finders:
            filename = self.finders.find(url2pathname(basename))
        if filename:
            return filename
        # or just raise an exception as the last resort
>       raise UncompressableFileError(
            "'%s' could not be found in the COMPRESS_ROOT '%s'%s" %
            (basename, settings.COMPRESS_ROOT,
             self.finders and " or with staticfiles." or "."))
E       compressor.exceptions.UncompressableFileError: 'js/vendors.js' could not be found in the COMPRESS_ROOT '/Users/omaciel/hacking/everycheese/staticfiles' or with staticfiles.

../../opt/miniconda3/envs/everycheese/lib/python3.8/site-packages/compressor/base.py:159: UncompressableFileError

 everycheese/cheeses/tests/test_views.py ⨯                                                                                                 25% ██▌       
 everycheese/users/tests/test_forms.py ✓                                                                                                   33% ███▍      
 everycheese/users/tests/test_models.py ✓                                                                                                  42% ████▎     
 everycheese/users/tests/test_urls.py ✓✓✓                                                                                                  67% ██████▋   
 everycheese/users/tests/test_views.py ✓✓✓✓                                                                                               100% ██████████

Results (1.62s):
      11 passed
       1 failed
         - everycheese/cheeses/tests/test_views.py:22 test_good_cheese_list_view_expanded
Can't add file tracer data for unmeasured file '/Users/omaciel/hacking/everycheese/everycheese/templates/cheeses/cheese_list.html'
```

**Comment by omaciel** [comment]
Hmmm `js/vendors.js` is indeed missing from my source code.

**Comment by pydanny** [comment]
@omaciel That's a bug we fixed in `django-crash-starter`. Looking at the text in the book it appears we didn't put a mitigation into the book for those working on the earlier version of the project. We'll provide instructions to fix it  in our next update.

**Comment by pydanny** [comment]
With a new build we've duplicated the `Can't add file tracer data for unmeasured file` message. Now we're trying to figure out how to correct it.

**Comment by pydanny** [comment]
This was resolved over a week ago.

🚢 🧀

**Comment by wilsonusman** [comment]
I'm using the latest book version. I'm not sure why I am I still seeing that message after I run:

`coverage run -m pytest
`

**My cheese_list.html**
```
{% extends "base.html" %}

{% block title %}Cheese List{% endblock title %}

{% block content %}
  <h2>Cheese List</h2>

<ul>
  {% for cheese in cheese_list %}
    <li><a href="{% url 'cheeses:detail' cheese.slug %}">{{ cheese.name }}</a></li>
  {% endfor %}
</ul>

<hr/>
<p>Don't see a cheese listed here?</p>
<p>
<a class="btn btn-primary"
href="{% url 'cheeses:add' %}" role="button">
Add Cheese
</a>
</p>

{% endblock content %}

```

**My test_views.py**
```
import pytest
from pytest_django.asserts import assertContains

from django.urls import reverse
from django.contrib.sessions.middleware \
    import SessionMiddleware
from django.test import RequestFactory

from everycheese.users.models import User
from ..models import Cheese
from ..views import (
    CheeseCreateView,
    CheeseListView,
    CheeseDetailView
)
from .factories import CheeseFactory

pytestmark = pytest.mark.django_db


# def test_good_cheese_list_view_expanded(rf):
#     # Determine the URL
#     url = reverse("cheeses:list")
#     # rf is pytest shortcut to django.test.RequestFactory
#     # We generate a request as if from a user accessing
#     # the cheese list view
#     request = rf.get(url)
#     # Call as_view() to make a callable object
#     # callable_obj is analogous to a function-based view
#     callable_obj = CheeseListView.as_view()
#     # Pass in the request into the callable_obj to get an
#     # HTTP response served up by Django
#     response = callable_obj(request)
#     # Test that the HTTP response has 'Cheese List' in the
#     # HTML and has a 200 response code
#     assertContains(response, 'Cheese List')

def test_good_cheese_list_view(rf):
    # Get the request
    request = rf.get(reverse("cheeses:list"))
    # Use the request to get the response
    response = CheeseListView.as_view()(request)
    # Test that the response is valid
    assertContains(response, 'Cheese List')

def test_good_cheese_detail_view(rf):
    # Order some cheese from the CheeseFactory
    cheese = CheeseFactory()
    # Make a request for our new cheese
    url = reverse("cheeses:detail",
        kwargs={'slug': cheese.slug}
    )
    request = rf.get(url)
    # Use the request to get the response
    callable_obj = CheeseDetailView.as_view()
    response = callable_obj(request, slug=cheese.slug)
    # Test that the response is valid
    assertContains(response, cheese.name)

def test_good_cheese_create_view(rf, admin_user):
    # Order some cheese from the CheeseFactory
    cheese = CheeseFactory()
    # Make a request for our new cheese
    request = rf.get(reverse("cheeses:add"))
    # Add an authenticated user
    request.user = admin_user
    # Use the request to get the response
    response = CheeseCreateView.as_view()(request)
    # Test that the response is valid
    assert response.status_code == 200
```
<img width="1076" alt="Screen Shot 2020-04-11 at 10 30 09 AM" src="https://user-images.githubusercontent.com/664387/79046529-77706700-7bdf-11ea-99cc-6541d5caf466.png">

**Comment by wilsonusman** [comment]
> I'm using the latest book version. I'm not sure why I am I still seeing that message after I run:
> 
> `coverage run -m pytest `
> 
> **My cheese_list.html**
> 
> ```
> {% extends "base.html" %}
> 
> {% block title %}Cheese List{% endblock title %}
> 
> {% block content %}
>   <h2>Cheese List</h2>
> 
> <ul>
>   {% for cheese in cheese_list %}
>     <li><a href="{% url 'cheeses:detail' cheese.slug %}">{{ cheese.name }}</a></li>
>   {% endfor %}
> </ul>
> 
> <hr/>
> <p>Don't see a cheese listed here?</p>
> <p>
> <a class="btn btn-primary"
> href="{% url 'cheeses:add' %}" role="button">
> Add Cheese
> </a>
> </p>
> 
> {% endblock content %}
> ```
> 
> **My test_views.py**
> 
> ```
> import pytest
> from pytest_django.asserts import assertContains
> 
> from django.urls import reverse
> from django.contrib.sessions.middleware \
>     import SessionMiddleware
> from django.test import RequestFactory
> 
> from everycheese.users.models import User
> from ..models import Cheese
> from ..views import (
>     CheeseCreateView,
>     CheeseListView,
>     CheeseDetailView
> )
> from .factories import CheeseFactory
> 
> pytestmark = pytest.mark.django_db
> 
> 
> # def test_good_cheese_list_view_expanded(rf):
> #     # Determine the URL
> #     url = reverse("cheeses:list")
> #     # rf is pytest shortcut to django.test.RequestFactory
> #     # We generate a request as if from a user accessing
> #     # the cheese list view
> #     request = rf.get(url)
> #     # Call as_view() to make a callable object
> #     # callable_obj is analogous to a function-based view
> #     callable_obj = CheeseListView.as_view()
> #     # Pass in the request into the callable_obj to get an
> #     # HTTP response served up by Django
> #     response = callable_obj(request)
> #     # Test that the HTTP response has 'Cheese List' in the
> #     # HTML and has a 200 response code
> #     assertContains(response, 'Cheese List')
> 
> def test_good_cheese_list_view(rf):
>     # Get the request
>     request = rf.get(reverse("cheeses:list"))
>     # Use the request to get the response
>     response = CheeseListView.as_view()(request)
>     # Test that the response is valid
>     assertContains(response, 'Cheese List')
> 
> def test_good_cheese_detail_view(rf):
>     # Order some cheese from the CheeseFactory
>     cheese = CheeseFactory()
>     # Make a request for our new cheese
>     url = reverse("cheeses:detail",
>         kwargs={'slug': cheese.slug}
>     )
>     request = rf.get(url)
>     # Use the request to get the response
>     callable_obj = CheeseDetailView.as_view()
>     response = callable_obj(request, slug=cheese.slug)
>     # Test that the response is valid
>     assertContains(response, cheese.name)
> 
> def test_good_cheese_create_view(rf, admin_user):
>     # Order some cheese from the CheeseFactory
>     cheese = CheeseFactory()
>     # Make a request for our new cheese
>     request = rf.get(reverse("cheeses:add"))
>     # Add an authenticated user
>     request.user = admin_user
>     # Use the request to get the response
>     response = CheeseCreateView.as_view()(request)
>     # Test that the response is valid
>     assert response.status_code == 200
> ```
> 
> <img alt="Screen Shot 2020-04-11 at 10 30 09 AM" width="1076" src="https://user-images.githubusercontent.com/664387/79046529-77706700-7bdf-11ea-99cc-6541d5caf466.png">

I think I figured it out. I was running "coverage run -m pytest"  from my project directory and not my actual app directory.

As soon as I cd into .../everycheese/everycheese the message went away. But I'm still not 100% sure if this is the correct solution.
